server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "Reports"
  profiles:
    active: local
aws:
  dynamodb:
    region: "${AWS_REGION:us-east-1}"
    profile: "${AWS_PROFILE:ivanmuza-labs-824013493466-AdministratorAccess}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:8080,http://localhost:8081,http://localhost:4200"
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queueUrl: "${AWS_SQS_PUBLISH_REPORT_QUEUE_URL}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
security:
  jwt:
    secret: "${JWT_SECRET}"