server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "Reports"
  profiles:
    active: "Prod"
aws:
  dynamodb:
    region: "${AWS_REGION:us-east-1}"
    profile: "${AWS_PROFILE:default}"
  region: "${AWS_REGION:us-east-1}"
  secretName: "prod/CrediYa/Reports/Secrets"
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
logging:
  level:
    com.credi.ya: INFO
    org.springframework: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queueUrl: "${AWS_SQS_PUBLISH_REPORT_QUEUE_URL}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 60
    numberOfThreads: 1